CREATE SEQUENCE SEQ_T_BOARD_FILE_NO;

CREATE TABLE T_BOARD_FILE (
	NO 				NUMBER(10) 		PRIMARY KEY,
	BOARD_NO 		NUMBER(6) 		NOT NULL,
	FILE_ORI_NAME 	VARCHAR2(100),
	FILE_SAVE_NAME 	VARCHAR2(100),
	FILE_SIZE 		NUMBER(10),
	REG_DATE  		DATE DEFAULT SYSDATE
);